### ISSUE TITLE
TLScrollView Updating

### ISSUE THREAD

**Issue by zanesc** [fabiocozzolino/TitiusLabs.Xamarin#1]
Hey, this is a really great, simple view that you made here. I am just a little confused by the rendering part of it.

I see there is a Render() in TLScrollView, does this not get called automatically? I seem to have to call it manually and then I have to call it each time i add items to the items list in order for it to render the new items. Am I doing something incorrectly or is this by design?

It isn't a big deal for me to call render manually, the only problem I have with it is that it scrolls back to the first item when ever i call render which is a bit inconvenient. Thanks for this view.

**Comment by akamud** [comment]
You probably forgot to use the Renderers for [iOS](https://github.com/fabiocozzolino/TitiusLabs.Xamarin/blob/master/TitiusLabs.Forms.iOS/Controls/TLScrollViewRenderer.cs) and [Android](https://github.com/fabiocozzolino/TitiusLabs.Xamarin/blob/master/TitiusLabs.Forms.Droid/Controls/TLScrollViewRenderer.cs).

**Comment by dazinator** [comment]
Looks like the renderers are no longer required as per the comments in the code.
