### ISSUE TITLE
Error in Render

### ISSUE THREAD

**Issue by andreluiz1987** [fabiocozzolino/TitiusLabs.Xamarin#2]
I create a new element in viewcell with a command but in renderer occurs an error in binding. Message Value cannot be null. Parameter name: element.

The error is here :  viewCell.View.BindingContext = item; Class TLScrollView Method Render()

My View:

`<ViewCell>
                                <StackLayout Padding="5">
                                    <AbsoluteLayout>
                                        <Image Source="{Binding Path}" HeightRequest="60" WidthRequest="60" Aspect="Fill" BackgroundColor="#D5D5D5" />
                                        <Image Source="icon.png" AbsoluteLayout.LayoutBounds="30, 0, 25, 30">
                                            <Image.GestureRecognizers>
                                                <TapGestureRecognizer Command="{Binding DeleteImage}" CommandParameter="{Binding .}"></TapGestureRecognizer>
                                            </Image.GestureRecognizers>
                                        </Image>
                                    </AbsoluteLayout>
                                </StackLayout>
                            </ViewCell> `

**Comment by fabiocozzolino** [comment]
Sorry for late reply, I assume you have found a solution. 
Thanks
