### ISSUE TITLE
Wiring up SelectedCommand to an ICommand on the Item.

### ISSUE THREAD

**Issue by dazinator** [fabiocozzolino/TitiusLabs.Xamarin#4]
I am just experimenting with the ItemsScrollView - thank you.

I can see you are wiring up the `SelectedCommand` to an event handler in the code behind.

I am attemtping to wire it up to an `ICommand` on the current item from the ItemsSource

```
<customControls:ItemsScrollView 
				Orientation="Horizontal" 
				ItemsSource="{Binding MyItems}" 				
				SelectedCommand="{Binding FooCommand}"                
				HeightRequest="100">

```

Each `Item` in `MyItems` has a property called `FooCommand` which is an `ICommand`. 
The BindingContext for the page is a ViewModel that has a "MyItems" property which is an observable collection.

Any ideas where I am going wrong?

**Comment by fabiocozzolino** [comment]
You need to put the command name into square brackets: `SelectedCommand="{Binding [FooCommand]}`
