### ISSUE TITLE
TLEntry reference in XAML

### ISSUE THREAD

**Issue by asdiomar1** [fabiocozzolino/TitiusLabs.Xamarin#5]
Tried to add the entry making reference in XAML, it worked but focus next button on keyboard is not appearing. If I do it in code behind works perfectly, But I wanted to use it in XAML since I have all my code in there.

**Comment by pdonovan** [comment]
Try `NextView=“{x:Reference Name=txtMyEntry}”`
Where the next Entry has `x:Name=“txtMyEntry”`
